### ISSUE TITLE
Installing witnet as systemd service

### ISSUE THREAD

**Issue by harsh-98** [witnet/witnet-operator-tools#5]
I was able to install witnet successfully after few tweaks.
On  `ubuntu 18.04.3 LTS`, `/etc/ssl/certs/ca-certificates.crt` was not present. So, either:
```
sudo apt-get install ca-certificates
```
or change to `/etc/ssl/certs/ca-bundle.crt` or remove the cafile flag altogether.

On `CentOS Linux 7 (Core)`, installing witnet failed as required GLIBC was not present. And there is no easy way to install it.

**Comment by bertux** [comment]
thank you @harsh-98 I will add ca-certificates to the Ubuntu packages to install
